
###
GET http://localhost:8081/api/v1/users
Accept: application/json

###

POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
  "name": "jack",
  "age": -1
}

###
POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
"name": "test",
"age": 20
}

###
PUT http://localhost:8081/api/v1/users/0
Content-Type: application/json

{
  "name": "test1",
  "age": 30
}

###
DELETE http://localhost:8081/api/v1/users/0
